#!/bin/sh

# 15 0 * * * rake_task_runner

`cd /var/www/backend-sac-platform/current && RAILS_ENV=staging rake members:cancel`
# billing should be executed after cancel jobs finishes
`cd /var/www/backend-sac-platform/current && RAILS_ENV=staging rake billing:send_prebill &`
`cd /var/www/backend-sac-platform/current && RAILS_ENV=staging rake members:process_fulfillments &`
`cd /var/www/backend-sac-platform/current && RAILS_ENV=staging rake billing:for_today`
