development:
  solr:
    hostname: localhost
    port: 8984
    log_level: DEBUG
    path: /solr/development
    auto_commit_after_request: false

production:
  solr:
    hostname: solr.stoneacrehq.com
    port: 8983
    log_level: WARNING
    path: /solr/production
    auto_commit_after_request: false
    # read_timeout: 2
    # open_timeout: 0.5

prototype:
  solr:
    hostname: solr.stoneacrehq.com
    port: 8983
    log_level: DEBUG
    path: /solr/prototype
    auto_commit_after_request: false

staging:
  solr:
    hostname: solr.stoneacrehq.com
    port: 8983
    log_level: DEBUG
    path: /solr/staging
    auto_commit_after_request: false

test:
  solr:
    hostname: localhost
    port: 8985
    log_level: WARNING
    path: /solr/test
    auto_commit_after_request: false
