#!/bin/bash

# 0 3 * * * /bin/sh /var/www/generate_reporting_database & >> /dev/null 2>&1

DATE=`date +"%Y-%m-%d_%H-%M-%S"`
MYSQL_USER=root
MYSQL_PASSWORD=pH03n[xk1{{s
SOURCE_DATABASE=sac_production
DESTINATION_DATABASE=sac_production_reporting
BACKUP_FILE_RAW=/tmp/backup_db$DATE

# stop slave and do backup
mysqladmin stop-slave -u $MYSQL_USER -p$MYSQL_PASSWORD
echo "generating backup"
mysqldump -u $MYSQL_USER -p$MYSQL_PASSWORD $SOURCE_DATABASE > $BACKUP_FILE_RAW

# start slave 
mysqladmin start-slave -u $MYSQL_USER -p$MYSQL_PASSWORD

# load backup into new database
mysql -u $MYSQL_USER -p$MYSQL_PASSWORD $DESTINATION_DATABASE < $BACKUP_FILE_RAW

# remove backup
rm $BACKUP_FILE_RAW
